config/routes.rb
Rails.application.routes.draw do
  resources :arts
  root "pages#home"
  get 'about', to: 'pages#about'
  resources :arts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/art.rb
class Art < ApplicationRecord
  validates :title, presence: true, length: {minimum:3, maximum:10}
  validates :description, presence: true, length: {minimum:3, maximum:10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def hello
    render html: 'Hello world'
  end

end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: %i[ show edit update destroy ]

  # GET /arts or /arts.json
  def index
    @arts = Art.all
  end


  # GET /arts/1 or /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts or /arts.json
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to art_url(@art), notice: "Art was successfully created." }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1 or /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to art_url(@art), notice: "Art was successfully updated." }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1 or /arts/1.json
  def destroy
    @art.destroy

    respond_to do |format|
      format.html { redirect_to arts_url, notice: "Art was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def art_params
      params.require(:art).permit(:title, :description, :user)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/arts/_art.html.erb
<div id="<%= dom_id art %>">

  <div>
    <p> Article <%= @art.id%> </p>
  </div>
  <p>
    <strong>Title:</strong>
    <%= art.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= art.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= art.user %>
  </p>


</div>

app/views/arts/_form.html.erb
<%= form_with(model: art) do |form| %>
  <% if art.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
        <% art.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <p> Article <%= @art.id%> </p>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

   <div>
    <%= form.label :user, style: "display: block" %>
    <%= form.text_field :user %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<h1>Editing art</h1>

<%= render "form", art: @art %><br>

<div>
  <%= link_to "Show this art", @art %> |
  <%= link_to "Back to arts", arts_path %>
</div>

app/views/arts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Arts</h1>

<div id="arts">
  <% @arts.each do |art| %>
    <%= render art %>
    <p>
      <%= link_to "Show this art", art %>
    </p>
  <% end %>
</div>

<%= link_to "New art", new_art_path %>

<h1> Showing list Articles  </h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th>Date created</th>
      <th>Date Updated</th>
      <th colspan ="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @arts.each do |art| %>
    <tr>
      <td><%= art.title %></td>
      <td><%= art.description %></td>
      <td><%= art.user %></td>
      <td><%= art.created_at %></td>
      <td><%= art.updated_at %></td>
      <td><%= link_to 'Show' , art_path(art.id) %> </td>
      <td><%= link_to 'Edit' , edit_art_path(art.id) %> </td>
      <td><%= link_to 'Delete', art_path(art), method: :delete %> </td>
    </tr>
    <% end %>
  </tbody>
</table>
<p>
<%= link_to 'Create New Art' , new_art_path %> 
</p>

app/views/arts/new.html.erb
<h1>New art</h1>

<%= render "form", art: @art %>

<br>

<div>
  <%= link_to "Back to arts", arts_path %>
</div>

app/views/arts/show.html.erb
<p style="color: green"><%= notice %></p>
<h1>Showing art</h1>

<%= render @art %>

<div>
  <%= link_to "Edit this art", edit_art_path(@art) %> |
  <%= link_to "Back to arts", arts_path %>
  <%= button_to "Destroy this art", @art, method: :delete %>
</div>

app/views/layouts/_messages.html.erb
    <%= flash.each do |name, msg|%>
     <%= msg %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Udemy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about</h1>


<%= link_to "Articles" , arts_path%> | 
<%= link_to "Home" , root_path%>

app/views/pages/home.html.erb
Hello world !!! 

<p>
<%= link_to "Articles", arts_path %> | 
<%= link_to "About" , about_path %>
</p>